### ISSUE TITLE
Tiny window on Mac

### ISSUE THREAD

**Issue by emlai** [SimonN/LixD#124]
Now that I got around #121, the program starts up properly, but the created window is _really_ small:

<img width="160" alt="screen shot 2016-07-19 at 13 10 30" src="https://cloud.githubusercontent.com/assets/7543552/16946457/4e3c4e3a-4db2-11e6-9e90-50762b0013ae.png">

I printed out the parameters of the [`al_create_display` call](https://github.com/SimonN/LixD/blob/85d909622df3c4fbfeff5c1c0f028e7a7b2282d1/src/hardware/display.d#L143) and they're both 0.

The values seem to come from [this line](https://github.com/SimonN/LixD/blob/85d909622df3c4fbfeff5c1c0f028e7a7b2282d1/src/hardware/display.d#L109), but I didn't find any documentation on `al_create_display` saying `0, 0` would be meaningful parameters to pass to it.

**Comment by SimonN** [comment]
Will look into it! Fullscreen is the default right now, and Allegro 5 should get the correct size from the system. The `0, 0` are dummy values that I thought would be ignored here. Maybe I should put something like `640, 480` in case they aren't ignored.

***

In the meantime, you can try one of these command-line parameters to get a better window:

    -w                      run windowed at 640x480
    --resol=800x600         run windowed at the given resolution
    --fullscreen            use software fullscreen mode (good Alt+Tab)
    --hardfull=1600x900     use hardware fullscreen at given resolution

**Comment by SimonN** [comment]
The default mode is now fullscreen with 640x480 passed for the command-line parameters. If fullscreen works, Allegro should ignore the given resolution. That should be a fallback for when fullscreen doesn't work. I hope this fixes the tiny window.

Once Lix runs, set the window resolution of your choice in the options menu.

**Comment by emlai** [comment]
Awesome, it works now!
