### ISSUE TITLE
Crash if zip files are in level folders

### ISSUE THREAD

**Issue by StephanNeupert** [SimonN/LixD#169]
Put a zip file in the directory lix/levels/single (with a file name not starting with "."). Then start Lix, click on "Single Player" and then move to the directory single/ in the level selection menu. Upon clicking on the "single/" button, Lix crashes with an object.Error message:
> object.Error@(0): assert(0) or HTL instruction

followed by 9 pointers to memory locations.
This bug was found using Lix version 0.6.22.

**Comment by SimonN** [comment]
Simon: What exact zip file did you use?
Nepster: NepsterLix_V1.4.zip
Simon: excellent, that file repros the crash
Simon: Lix parses the archive as a level, D defaults to unicode-decoding, throws because of malformed UTF
