### ISSUE TITLE
Reappearing terrain in multiplayer

### ISSUE THREAD

**Issue by nstbayless** [SimonN/LixD#177]
Terrain reappears about 0.5-2 seconds after disappearing, not always consistent in timing, seems to happen either when a packet arrives, or the mouse hovers over a lix, or a skill is assigned, but I'm not certain how consistent it is.

![lix_missing_terrain](https://cloud.githubusercontent.com/assets/7698597/24083781/1ab23a54-0c9b-11e7-9887-abc403c46c89.png)

The physics still behaves as though the terrain is missing but the terrain resets. Notably, additive changes to the terrain (such as builders) do persist, and destroying the bridges later also causes them to reappear just like other terrain.

**Comment by SimonN** [comment]
Thanks for the image and thorough explanation!

From discussion with nstbayless in voicechat:

* Recently-destroyed terrain shows again
* Can happen 1.5 seconds when a packet arrives. Can happen at other times.
* This terrain is hollow, i.e., physics remain correct. Only the image is wrong.

**Comment by nstbayless** [comment]
Also, I should point out that I played on the provided build, rather than compiling from source: http://www.lixgame.com/dow/lix-d-port.7z
