### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by SimonN** [SimonN/LixD#212]
Lix 0.8

Play music during levels and during the menu.

Ideally, allow for oggs and tracked music, on both Windows and Linux.

On Arch Linux, Allegro 5 doesen't depend on DUMB. I've emailed the A5 Arch package maintainer. Will see how this evolves!

**Comment by wrathix** [comment]
If music is something you are seriously considering to be in Lix, i'll be motivated to make more tunes.
I have 2 made already which some of you have heard.

**Comment by SimonN** [comment]
Hi Rubix,

I'm still undecided whether I'd like to push oggs or tracked music (xm, it, s3m, mod). I have a soft spot for tracked music.

Including a couple oggs in the standard download is fine in any case. For many oggs, I'd split the pack into low-quality and high-quality soundtrack. But I've earmarked your menu theme (Lix Menu Beta 1.0) no matter what happens.

**Comment by SimonN** [comment]
Lix 0.9.3 supports music. Create directory `./music/`, create a subdirectory for your own files, and Lix will play ogg, xm, s3m, it, mod.

You can [download Lix's music pack](http://www.lixgame.com/dow/lix-music.zip) and extract it into Lix's root dir.
