### ISSUE TITLE
Deselect old skill when pressing hotkey of empty skill

### ISSUE THREAD

**Issue by SimonN** [SimonN/LixD#229]
Lix 0.8.5

Rubix suggested this:

> When you select a skill that is already depleted, you get the beep sound. But the selection stays on your current skill you were last using. This for some dumb reason constantly messes up in my mind and I'll waste a skill or just fumble with keys , and I dont know why. It should have come natural that if it beeps, I havent switched to a new skill yet, so pick anther skill NOW.
>
> What I actually would prefer personally, is it it DID switch to the skill that you want, even with it being depleated.  Then when you try use it you get the BEEP error
>
> I like that there's an error sound, but i want to have switched to the skill that is empty, then when I try use it ill get the beep instead

I have the same issue. Very sensible idea.

**Comment by wrathix** [comment]
Thanks, I would love to see this changed.   I feel I can definitely play better and stumble less.
Rub
