### ISSUE TITLE
Tag releases in Git

### ISSUE THREAD

**Issue by Rondom** [SimonN/LixD#232]
In order to make it easier to find the source code for a specific release could you tag the commits corresponding to the releases?
For example for the latest version 0.8.5 I assume:

    git tag -a v0.8.5 a2b7c3fe224eea7cbff8e2dc647f3541d9b8e95d

**Comment by SimonN** [comment]
Hi, thanks for taking a look! Will tag 0.8.5 and upcoming versions.

Only a week ago, I added installability according to the FHS, which allows Linux packaging, that makes tags more important.

**Comment by SimonN** [comment]
I've switched to annotated tags since 0.8.8.
