### ISSUE TITLE
Feature request: Hotkey to save screenshots.

### ISSUE THREAD

**Issue by stavrossk** [SimonN/LixD#288]
Hi, like replays, I like to save screenshots when I play to review my progress later on.
I know there are external tools to save screenshots, but I think it would be a great feature for Lix to have a hoktey to save PNG or JPG screenshots to the game's "Screenshots" sub-directory.
Optimally the hotkey could be Print Screen of F12 (like Steam), but it would also be nice if the key could be configurable.

Thanks,
Stavros.

**Comment by SimonN** [comment]
How do you plan to use this? Do you take many screenshots in a single session, then keep most of those?

If you're on Windows: You can screenshot exactly the focused application with `Alt` + `Printscreen`, then paste that into an image program. Have you tried this single-app screenshotting and it's not enough for your purpose?

**Comment by stavrossk** [comment]
@SimonN I want to take multiple screenshots at a single play sessiong without leaving the game. 

I would like the program to automatically increment the number of each screenshot, optionally the filename containing the level's name, e.g. Lix-Any_Way_You_Want-001.png Lix-Any_Way_You_Want-002.png etc. 

I know that Windows can take a single screenshot with Print Screen but it's too much of a hassle to leave the game, paste into an image program and finally save the image manually. I would like the screenshot saving process to be made automatically from the game itself.

**Comment by SimonN** [comment]
Yeah, for such excessive screenshotting, an ingame feature is indeed best.

I'll look into it!

**Comment by stavrossk** [comment]
@SimonN Thanks for looking into it!

**Comment by SimonN** [comment]
I implemented screenshots in unstable: A rebindable hotkey that saves auto-named and auto-numbered screenshots throughout the entire application, without a default binding (you can bind it in the options menu to, e.g., F12).

Will be included in 0.9.9, which should release in a couple days!

**Comment by stavrossk** [comment]
@SimonN Thanks a lot, can't wait to try it out!

**Comment by SimonN** [comment]
0.9.9 has been out for 2 days. I don't have automatic annoucements on the Lix homepage >_>; But maybe you've already found it.
