### ISSUE TITLE
No way to add explicit space character in translation?

### ISSUE THREAD

**Issue by Wuzzy2** [SimonN/LixD#340]
Apparently there is no way to add a space explicitly into a translation file when it is leading or trailing. All trailing and leading spaces appear to be completely removed.

This can be a problem. In the German translation, there is one problematic string when you start a room in net play:

> Du hast Raum Nr\.1betreten.

(“You have entered room #1.”)

2 spaces are missing. It should be:

> Du hast Raum Nr\. 1 betreten.

**Comment by Wuzzy2** [comment]
Arrrrghh! I hate GitHub. The “Nr.” above should be “Nr” followed by a period. GitHub messes up my string when I enter “N”, “r”, “.” … Grrrrrrrrrrr.

**Comment by SimonN** [comment]
Limitation of the translation file format, yes. I hoped that spaces were never needed at start/end of string.

When I translate such strings, I should offer the entire line as one string-to-translate, including the variable that the program fills later:
```Du hast Raum Nr. %d betreten.```
The spaces are then in the middle and won't be pruned. It's also easier to read for the translator.

**Comment by Wuzzy2** [comment]
I agree, using format strings is much better.
