### ISSUE TITLE
Editor: Mirror icon is wrong

### ISSUE THREAD

**Issue by Wuzzy2** [SimonN/LixD#349]
In Lix 0.9.17, the icon for mirroring an object (horizontally) looks wrong. The arrows go up/down, but this suggests the mirror is vertical.

The arrows should go left/right instead beause this tool only mirrors objects horizontally, not vertically.

**Comment by SimonN** [comment]
Duplicate of #115 Editor, single flip button inconsistent, make 2nd button.

I agree, there should be an icon to mirror horizontally.
