### ISSUE TITLE
Tooltip for splat ruler is incorrect

### ISSUE THREAD

**Issue by Wuzzy2** [SimonN/LixD#350]
In 0.9.17, the tooltip for the splat ruler says:

“Show splat ruler, hatches, goals.”

This is wrong.

Only the first part is correct. But no hatches or goals are shown, they look exactly the same when I activate this.

**Comment by SimonN** [comment]
Yes, this tooltip should be changed according to what the button does (different in singleplayer/multiplayer).

See also #301 Separate ping-exit and splatruler button.
