### ISSUE TITLE
New multiplayer exit symbols messed up

### ISSUE THREAD

**Issue by geoo89** [SimonN/LixD#372]
The new symbols over the exits in multiplayer (X and arrow) are bugged for me.

Lix version: 0.9.22
dmd version: 2.083
Allegro version: 5.2.4.0
OS: Ubuntu 14.04 LTS

![bad_exit_symbols2](https://user-images.githubusercontent.com/678199/49333346-9a3b4600-f5bd-11e8-8854-a4b6c78bd2e3.png)
![bad_exit_symbols1](https://user-images.githubusercontent.com/678199/49333347-9a3b4600-f5bd-11e8-9933-f0491069d6b6.png)

**Comment by SimonN** [comment]
Thanks!

* The bright left edge is recolored properly.
* The center and dark edges aren't recolored.
* The partly transparent arrow even produces stray pixels within its rectangular sprite boundaries that look like memory garbage.

I conjecture that some color channels have been swapped, but I haven't investigated yet. Allegro allows for different color orderings in the data. It's strange that this happens only with these recently-introduced exit markers.

**Comment by SimonN** [comment]
I can repro this on my laptop (some specs below) but not on my desktop (Nvidia dedicated graphics card). Both run Arch Linux.

Laptop `lspci` output:
```
00:00.0 Host bridge: Intel Corporation 8th Gen Core Processor Host Bridge/DRAM Registers (rev 08)
00:02.0 VGA compatible controller: Intel Corporation 8th Gen Core Processor Gaussian Mixture Model
```

**Comment by SimonN** [comment]
With Allegro debugging libraries, the laptop doesn't show anything out of the ordinary in `allegro.log`.

Most likely, I'll replace the semitransparent frame with all-or-nothing-transparency per pixel.

I should also reduce this bug, but it will be hard because the repro is so inconsistent. It's easier to repro this when Lix has already recolored and drawn a lot in the same run of the app before loading the exit marker.

**Comment by SimonN** [comment]
Closing this because I've changed the offending file to have no alpha channel anymore. All pixels are either fully transparent (black in the file) or fully opaque.

The weirdness still exists somewhere in Lix (likely) or in Allegro 5, it's merely never invoked.
