### ISSUE TITLE
HTTPS for www.lixgame.com ?

### ISSUE THREAD

**Issue by szpak** [SimonN/LixD#422]
A minor issue, but for people enforcing HTTPS everywhere it is an extra procedure to add an exception visiting the page (and decrease own security :-) ). I don't know where you host it, but maybe it would be possible and not very problematic to add Let's Encrypt integration?

**Comment by SimonN** [comment]
Yeah, it's rare to see raw HTTP, but I didn't know some people outright refuse it by default. Thanks for the prod.

Let's Encrypt should be possible. I host lixgame.com on a virtual private server, I have admin rights and can install what I like. I've never looked into adding HTTPS before and I'd learn something new from it.

I'll keep it in the back of the mind -- I'm still busy with other things in Lix, I won't look into HTTPS immediately.

**Comment by SimonN** [comment]
My New Year's Resolution is to add HTTPS. I'll look into it these weeks!

**Comment by SimonN** [comment]
@szpak: Have a look at https://www.lixgame.com. HTTPS should work, and I redirect all `http://` to `https://`. Indeed I chose Let's Encrypt.

Thanks for prodding me to start. It's a wide topic, lots to learn still, and I'll continue to toy with minor details and configuration in the future.

**Comment by szpak** [comment]
It seems to work fine, thanks!
