### ISSUE TITLE
Hatch-less levels playable as next level

### ISSUE THREAD

**Issue by geoo89** [SimonN/LixD#466]
When a level is missing a hatch, it cannot be played from the browser.

However, it can be played as the "next level" from the end-of-level dialog of the previous level, causing the game to crash.

**Comment by SimonN** [comment]
This bug is in the current 0.10.11 and likely too in all older versions with the next-level screen.

Good find, thanks!

**Comment by SimonN** [comment]
This is now fixed in my [unstable repo](https://github.com/SimonN/lix-unstable) and will go into 0.10.12, which should release in the next few days.
