### ISSUE TITLE
Lobby ready-up desync

### ISSUE THREAD

**Issue by Dullstar** [SimonN/LixD#480]
Observed during 1/27/2024 lemforum session on central server.

A player dropped and rejoined. The other players in the lobby remained visibly readied up, but when all players were shown as ready, the game did not start. Appears there was a desync at some point. My client version is 0.10.18, compiled from source (I know I wasn't the only one affected, but I'm not sure what version everyone's client was or exactly how many players were affected; I want to say one or two people may have still been on 0.10.17).

I tried to reproduce this with a locally hosted server; the observed behavior was that a player leaving and rejoining would unready all players in the lobby. I need to do some further testing e,g. if the client crashes somehow. I don't know what version of the server is running on the central one; I'd assume it's probably up-to-date but have no way to confirm. The locally hosted one I used to test should be 0.10.18.

**Comment by SimonN** [comment]
Repro against 0.10.18 lixserv:

1. Open 3 clients and have them all connect to the same server. _Don't enter_ a room yet; stay in the lobby. Make the clients different colors, let's say, red, green, blue.

2. Red and green enter the same room.

Blue is waiting outside the room.

3. Red picks a level.

Now is the first time that anybody is even able to press ready. Blue is still outside.

4. Red presses ready.

You'll see that red and green agree on all ready statuses in the room: Both red and green believe that red is ready and that green is not ready yet.

5. Blue enters the room.

Here, we see the first desync: Blue believes that nobody is ready. Red believes that only red is ready. Green agrees that only red is ready. This is the heart of the bug: After you've entered a room of players with mixed readiness, the players in the room necessarily agree on who's ready.

5. Both green and blue press ready.

Here, both red and green see the topic's bug. Both red and green now think that everybody is ready, and they're surprised that the game won't start. Blue thinks that only green and blue are ready and that red isn't ready yet.

6. Red unreadies, then readies again.

This works around the bug. Now, the game starts. I believe that, after step 5, lixserv agreed with the blue player: Nobody was ready after blue entered the room, and to start a game, it wasn't enough for only green and blue to press ready.

**Comment by SimonN** [comment]
This will be a client-side fix (unready all when new peer joins the room) and won't need a server-side fix. It can go into any next version, no need to bump the minor version x.Y.z.

Separately from this (unready all when peer joins), it's conceivable to preserve everybody's ready status when an observer joins. But that will be both a client change and a server change. I'd only do this for 0.11, and will have to remember to do it then.

**Comment by SimonN** [comment]
Fixed in 0.10.19 on the client side.
